#!/usr/bin/ruby

# Shift array element iteratively
def shifter(ids)
  a, i = ids[0], 0
  while i + 1 < ids.length
    ids[i] = ids[i + 1]
    i += 1
  end
  ids[i] = a
  ids
end

ids =  ARGF.read.strip.split(",")
puts shifter(ids).join(",")